# Function Definitions

In [1]:
import pandas as pd 
import numpy as np

In [2]:
def load_date(file_path):
    df = pd.read_csv(file_path, encoding='utf-8')
    print("Shape of dataframe:", df.shape)
    return df

In [3]:
def add_column_index(df):
    df.insert(0, "index", range(1, len(df) + 1))
    return df

In [4]:
def Clean_Binaries(df, col, mapping):
    print(f"{col} unique values:\n", df[col].unique())
    
    # Convert to binary values and clean it:
    # Words that are not in the mapping, will be converted to NaN
    df[col] = df[col].str.strip()
    df[col] = df[col].map(mapping)
    print(f"{col} unique values after process:\n", df[col].unique())

    return df

In [5]:
def check_null_dup(df, col):
       
    if df1[df1[col].isna()].shape[0] != 0:
        print(f"Null {col} Found!")
    else:
        print(f"No Null {col}")
        
    if len(df[col].unique()) != df.shape[0]:
        if df[df.duplicated(col, keep=False)].shape[0] != 0:
            print(f"Duplicated {col}!")
            print(df[df.duplicated(col, keep=False)][["index", col]])

In [6]:
def user_regex(df, col, reg):
    print(f"{col} unique values:\n", df[col].unique())

    # Extract matched ones from strings and make all others, nan
    df[col] = (
        df[col]
        .astype(str)
        .str.extract(reg, expand=False)  
        .astype(float)
    )
    print(f"{col} unique values after process:\n", df[col].unique())
    return df

In [7]:
def Clean_Numerics(df, col, mapping):
    print(f"{col} unique values:\n", df[col].unique())

    # 1. Convert to valid values:
    # Words that are not in the mapping, will be unchanged
    df[col] = df[col].replace(mapping)

    # 2. Convert numeric-looking values to number, errors become NaN
    df[col] = pd.to_numeric(df[col], errors="coerce")
    
    print(f"{col} unique values after process:\n", df[col].unique())

    return df

In [8]:
def not_numbers_to_nan(df, col):
    print(f"{col} unique values:\n", df[col].unique())

    df[col] = pd.to_numeric(
        df[col].astype(str).str.strip(),
        errors="coerce"
    )
    
    print(f"{col} unique values after process:\n", df[col].unique())
    return df

In [9]:
def clean_length_cols(df, col):
    print(f"{col} unique values:\n", df[col].unique())

    s = df[col].astype(str)
    
    mm_vals = s.str.extract(r'(\d+(?:[.,]\d+)?)\s*mm', expand=True)[0]  # integer OR decimal number (',' or '.' as decimal separator) + zero or more spaces + "mm"
    
    num_vals = s.str.extract(r'^\s*(\d+(?:[.,]\d+)?)\s*$', expand=True)[0] # string must contain only a number (optionally with spaces around it)
    
    # Combine the extracted values, filling NaNs from mm_vals with num_vals
    combined_vals = mm_vals.fillna(num_vals)
    
    # Replace comma with dot for decimal conversion and convert to numeric
    df[col] = pd.to_numeric(
        combined_vals.str.replace(',', '.', regex=False),
        errors="coerce"
    )
    
    print(f"{col} unique values after processing:\n", df[col].unique())

    return df

# Load Data & Index Column

In [10]:
df1 = load_date("eng_col_data/n2_col_renamed.csv")

# add a column as unique IDs
df1 = add_column_index(df1)
df1.head()

Shape of dataframe: (123, 69)

,index,id,moth_age,moth_weight,moth_height,preeclampsia,parent_relat,race,num_preg,num_births,...,lungs_eval,diaphragm_eval,abd_wall_nb_eval,stomach_eval,kidney_eval,fetal_bladder_eval,placenta_vessels_eval,fetal_limbs_eval,nb_attachment_eval,spinal_processes_eval
0,1,2476491.0,29,ندارد,ندارد,ندارد,گزارش نشده,گزارش نشده,2,2,...,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال
1,2,2368629.0,18,ندارد,ندارد,ندارد,غیر منسوب,ایرانی,1,1,...,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال
2,3,2629535.0,31,ندارد,ندارد,ندارد,غیر منسوب,ایرانی,2,2,...,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال
3,4,1012353.0,36,ندارد,ندارد,ندارد,غیر منسوب,اتباع,4,4,...,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال
4,5,2615589.0,25,78.8,ندارد,ندارد,گزارش نشده,گزارش نشده,4,4,...,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال

In [11]:
# Change the position of one column to make it like two other dataframes
col = "preeclampsia"
df1[col] = df1.pop(col)    # remove it and append to the end
df1.head()

,index,id,moth_age,moth_weight,moth_height,parent_relat,race,num_preg,num_births,num_stillborns,...,diaphragm_eval,abd_wall_nb_eval,stomach_eval,kidney_eval,fetal_bladder_eval,placenta_vessels_eval,fetal_limbs_eval,nb_attachment_eval,spinal_processes_eval,preeclampsia
0,1,2476491.0,29,ندارد,ندارد,گزارش نشده,گزارش نشده,2,2,0,...,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال,ندارد
1,2,2368629.0,18,ندارد,ندارد,غیر منسوب,ایرانی,1,1,0,...,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال,ندارد
2,3,2629535.0,31,ندارد,ندارد,غیر منسوب,ایرانی,2,2,0,...,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال,ندارد
3,4,1012353.0,36,ندارد,ندارد,غیر منسوب,اتباع,4,4,0,...,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال,ندارد
4,5,2615589.0,25,78.8,ندارد,گزارش نشده,گزارش نشده,4,4,0,...,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال,نرمال,ندارد

# Binary Columns
34 columns

## Columns (A-Z)

In [12]:
print("-- Check Parent Relationship")
col = "parent_relat"
print(f"{col} unique values:\n", df1[col].unique())

# Normalize text
s = df1[col].astype(str).str.lower().str.strip()

df1[col] = np.select(
    [
        s.str.contains(r'غیر', na=False),
        s.str.contains(r'منسوب', na=False)
    ],
    [0, 1],
    default=np.nan
)

print(f"{col} unique values after process:\n", df1[col].unique())

-- Check Parent Relationship
parent_relat unique values:
 ['گزارش نشده' 'غیر منسوب' 'منسوب' 'ندارد' 'نبود' 'غیرمنسوب']
parent_relat unique values after process:
 [nan  0.  1.]

In [13]:
print("-- Check Race")
col = "race"
print(f"{col} unique values:\n", df1[col].unique())

# Normalize text
s = df1[col].astype(str).str.lower().str.strip()

df1[col] = np.select(
    [
        s.str.contains(r'ایرا|ابرانی', na=False),
        s.str.contains(r'ات|افغ', na=False)
    ],
    [1, 0],
    default=np.nan
)

print(f"{col} unique values after process:\n", df1[col].unique())

-- Check Race
race unique values:
 ['گزارش نشده' 'ایرانی' 'اتباع' 'ابرانی' 'ندارد' 'اتباع ' 'نبود']
race unique values after process:
 [nan  1.  0.]

In [14]:
print("-- Check Privous Prem Birth")
col = "prev_prem_birth"
mapping = {
    "ندارد": 0,
    "ندارذ": 0,
    "ندازد": 0,
    "0": 0
}
df1 = Clean_Binaries(df1, col, mapping)

-- Check Privous Prem Birth
prev_prem_birth unique values:
 ['0' 'گزارش نشده' 'ندارد']
prev_prem_birth unique values after process:
 [ 0. nan]

In [15]:
print("-- Check Delivery Method")
col = "delivery_method"
print(f"{col} unique values:\n", df1[col].unique())

# Set labels to 0 or 1
s = df1[col].astype(str).str.strip()

# THIS MAY CHANGE IN ANOTHER FILES!!!!!!!
cesarean = s.str.contains(r'سزار|اول', na=False)   # -> 1
vaginal = s.str.contains(r'طبیعی|واژینال', case=False, na=False)  # -> 0

df1[col] = np.select(
    [cesarean, vaginal],
    [1, 0],
    default=np.nan
)

print(f"{col} unique values after process:\n", df1[col].unique())

-- Check Delivery Method
delivery_method unique values:
 ['طبیعی' 'واژینال']
delivery_method unique values after process:
 [0.]

In [16]:
print("-- Check Previous PPROM")
col = "prev_pprom"
print(f"{col} unique values:\n", df1[col].unique())

# Normalize text
s = df1[col].astype(str).str.lower().str.strip()

df1[col] = np.select(
    [
        s.str.contains(r'خی|ندا', na=False),
        s.str.contains(r'rom|اکنون|دارد', na=False)
    ],
    [0, 1],
    default=np.nan
)

print(f"{col} unique values after process:\n", df1[col].unique())

-- Check Previous PPROM
prev_pprom unique values:
 ['ندارد' 'دارد' 'اکنون']
prev_pprom unique values after process:
 [0. 1.]

In [17]:
print("-- Check Previous Heart Disease")
col = "prev_heart_disease"
print(f"{col} unique values:\n", df1[col].unique())

# Normalize text
s = df1[col].astype(str).str.lower().str.strip()

# Patterns
no_result = s.str.contains(r'برادی کاردی|پرکاری|پر کاری', na=False)

disease = s.str.contains(r'تیروئید|بله|فشار|تومور|زجر', na=False)

no_disease = s.str.contains(r'خیر|حیر|ندارد', na=False)

df1[col] = np.select(
    [no_result, disease, no_disease],
    [np.nan, 1, 0],
    default=np.nan
)

print(f"{col} unique values after process:\n", df1[col].unique())

-- Check Previous Heart Disease
prev_heart_disease unique values:
 ['ندارد']
prev_heart_disease unique values after process:
 [0.]

In [18]:
print("-- Check Previous Minor Thalasemy")
col = "prev_minor_thal"
print(f"{col} unique values:\n", df1[col].unique())

# Normalize text
s = df1[col].astype(str).str.lower().str.strip()

df1[col] = np.select(
    [
        s.str.contains(r'تالاسمی مینور دارد', na=False),
        s.str.contains(r'خی|ندارد', na=False)
    ],
    [1, 0],
    default=np.nan
)

print(f"{col} unique values after process:\n", df1[col].unique())

-- Check Previous Minor Thalasemy
prev_minor_thal unique values:
 ['ندارد' 'تالاسمی مینور دارد']
prev_minor_thal unique values after process:
 [0. 1.]

In [19]:
print("-- Hbs-Ag")
col = "hbs_ag" 
print(f"{col} unique values:\n", df1[col].unique())

# Normalize text
s = df1[col].astype(str).str.lower().str.strip()

# Patterns
neg_pattern = r'منفی|negetive|نان ریاکتیو|منقی|نرمال|manfi'
pos_pattern = r'مثبت|positive|غیرنرمال'

# Conditions according to words and numbers
is_positive = s.str.contains(pos_pattern, na=False)
is_negative = s.str.contains(neg_pattern, na=False)

df1[col] = np.select(
    [is_positive, is_negative],
    [1, 0],
    default=np.nan
)

print(f"{col} unique values after process:\n", df1[col].unique())

-- Hbs-Ag
hbs_ag unique values:
 ['نرمال' 'درخواست نشده']
hbs_ag unique values after process:
 [ 0. nan]

In [20]:
print("-- Urine Culture")
col = "urine_culture" 
print(f"{col} unique values:\n", df1[col].unique())

s = df1[col].astype(str).str.lower().str.strip()

# Patterns
no_test = s.str.contains(
    r'درخواست نشده|ذکر نشده|zekr|ندارد|nadarad|nadasht|ذکر نشذه',
    na=False
)
growth = s.str.contains(
    r'e\.?coli|kleb|strep|entro|candida|lacto|استاف|اپید|کلبسیلا|دیفترو|'
    r'کاندیدا|باکتری|mixed|growth|moderate|many|few|مثبت|لاکتوبا|ای کولای|bacterial'
    r'استرپ|diphtheroid|staph|ساپروفیتیکوس|ای کلای',
    na=False
)
normal = s.str.contains(r'نرمال|منفی|normal|منقی', na=False)

df1[col] = np.select(
    [no_test, growth, normal],
    [np.nan, 1, 0],
    default=np.nan
)

print(f"{col} unique values after process:\n", df1[col].unique())

-- Urine Culture
urine_culture unique values:
 ['نرمال' 'استافیلوکوک اپیدرمیس' 'درخواست نشده' 'لاکتوباسیل' 'E.coli'
 'ساپروفیتیکوس' 'moderate mix' 'ای کلای']
urine_culture unique values after process:
 [ 0.  1. nan]

In [21]:
print("-- Syphilis Screening VDRL")
col = "syphilis_screening_vdrl" 
print(f"{col} unique values:\n", df1[col].unique())

s = df1[col].astype(str).str.strip().str.lower()

df1[col] = np.select(
    [
        s.str.contains('منفی|منقی|نرمال|normal', na=False),
        s.str.contains('مثبت|positive', na=False)
    ],
    [
        0,  # negative
        1   # positive (not exist here. future safe!)
    ],
    default=np.nan
)
print(f"{col} unique values after process:\n", df1[col].unique())

-- Syphilis Screening VDRL
syphilis_screening_vdrl unique values:
 ['نرمال' 'درخواست نشده']
syphilis_screening_vdrl unique values after process:
 [ 0. nan]

In [22]:
print("-- Glucose Tolerance Test Results")
col = "glucose_tolerance_test"
df1 = not_numbers_to_nan(df1, col)

df1[col] = np.select(
    [df1[col] <= 120, df1[col] > 120],
    [0, 1],
    default=np.nan
)

print(f"{col} unique values after process:\n", df1[col].unique())

-- Glucose Tolerance Test Results
glucose_tolerance_test unique values:
 ['117' '90' '131' '107' '125' '124' '80' 'درخواست نشده' '95' 'نمونه نداده'
 '102' '99' '120' '92' '136' '106' '100' '82' '143' '70' '55' '97' '75'
 '110' '89' '91' '126' '94' '56' '86' '96' '77' '115' '146' '72' '119'
 '101' '137' '85' '87' '79' '76' '84' '148' '104' '83' '109' '111' '141']
glucose_tolerance_test unique values after process:
 [117.  90. 131. 107. 125. 124.  80.  nan  95. 102.  99. 120.  92. 136.
 106. 100.  82. 143.  70.  55.  97.  75. 110.  89.  91. 126.  94.  56.
  86.  96.  77. 115. 146.  72. 119. 101. 137.  85.  87.  79.  76.  84.
 148. 104.  83. 109. 111. 141.]
glucose_tolerance_test unique values after process:
 [ 0.  1. nan]

## Columns (AA-AZ)

In [23]:
print("-- Ventriculomegaly")
col = "ventriculomegaly"
# Numeric binary (normal (no ventriculomegaly) = 0, ventriculomegaly = 1)
mapping = {
    "نرمال": 0,
    "نزمال": 0,
    "دارد": 1
}
df1 = Clean_Binaries(df1, col, mapping)

-- Ventriculomegaly
ventriculomegaly unique values:
 ['نرمال' 'دارد']
ventriculomegaly unique values after process:
 [0 1]

In [24]:
print("-- Hyper Echo Intestines")
col = "hyper_echo_intestines"
mapping = {
    "نرمال": 0,
    "نزمال": 0,
    "ننرمال": 0,
    "دارد": 1
}
df1 = Clean_Binaries(df1, col, mapping)

-- Hyper Echo Intestines
hyper_echo_intestines unique values:
 ['نرمال' 'دارد']
hyper_echo_intestines unique values after process:
 [0 1]

In [25]:
print("-- Intra Cardiac Exho Focus")
col = "intra_cardiac_echo_focus"
print(f"{col} unique values:\n", df1[col].unique())

s = df1[col].astype(str).str.strip()

# 0 = normal/absent  &  1 = intracardiac echogenic focus present
df1[col] = np.select(
    [
        s.str.contains('دارد', na=False),
        s.str.contains(r'\d', na=False),
        s.str.contains('نرمال|نزمال|نرکال|نمرال', na=False)
    ],
    [
        1,  # presence
        1,  # numeric sizes like 2mm
        0   # normal
    ],
    default=np.nan
)

print(f"{col} unique values after process:\n", df1[col].unique())

-- Intra Cardiac Exho Focus
intra_cardiac_echo_focus unique values:
 ['نرمال' 'نمرال' 'ضایعه اکوژن ۲*۲ بطن چپ' 'سایز 1.8mm در بطن راست'
 'ضایعه اکوژن ۲.۸ بطن راست' 'دارد' 'ضایعه اکوژن ۱.۶ بطن چپ']
intra_cardiac_echo_focus unique values after process:
 [0. 1.]

In [26]:
print("-- Choroid Plexus Cyst")
col = "choroid_plexus_cyst"
print(f"{col} unique values:\n", df1[col].unique())

# Normalize text
s = df1[col].astype(str).str.lower().str.strip()

# Patterns
no_cyst = r'نرمال|نزمال'
has_cyst = r'کیست دارد'

# Conditions according to words and numbers
positive = s.str.contains(has_cyst, na=False) 
negative = s.str.contains(no_cyst, na=False) 

df1[col] = np.select(
    [positive, negative],
    [1, 0],
    default=np.nan
)

print(f"{col} unique values after process:\n", df1[col].unique())

-- Choroid Plexus Cyst
choroid_plexus_cyst unique values:
 ['نرمال' 'کیست دارد' 'کیست دارد 8*4.5' 'کیست دارد R 2.5,3.8و L 2'
 'کیست دارد R 11*7و L 13*7']
choroid_plexus_cyst unique values after process:
 [0. 1.]

In [27]:
print("-- Pyelectasis")
col = "pyelectasis"
print(f"{col} unique values:\n", df1[col].unique())

s = df1[col].astype(str).str.strip()

df1[col] = np.select(
    [
        s.str.contains('رویت|دارد', na=False),
        s.str.contains(r'\d+\.', na=False),
        s.str.contains('نرمال|نزمال', na=False)
    ],
    [
        1,  # presence
        1,  # measurements like 3.5L/2.6R
        0   # normal
    ],
    default=np.nan
)

print(f"{col} unique values after process:\n", df1[col].unique())

-- Pyelectasis
pyelectasis unique values:
 ['نرمال' 'سمت چپ 4.4mm' 'دارد']
pyelectasis unique values after process:
 [0. 1.]

In [28]:
print("-- Skull Structure")
col = "skull_structure_anomaly_scan"
# Numeric binary (normal = 0, abnormal = 1)
mapping = {
    "نرمال": 0,
    "سفال هماتوم ": 1,
    "سفال هماتوم خفیف": 1
}
df1 = Clean_Binaries(df1, col, mapping)

-- Skull Structure
skull_structure_anomaly_scan unique values:
 ['نرمال' ' نرمال']
skull_structure_anomaly_scan unique values after process:
 [0]

In [29]:
print("-- Choroid Plexus")
col = "choroid_plexus_anomaly_scan"
print(f"{col} unique values:\n", df1[col].unique())

s = df1[col].astype(str).str.strip()

df1[col] = np.select(
    [
        s.str.contains('نرمال|نزمال', na=False),
        s.str.contains(r'\d|کیست', na=False)
        
    ],
    [
        0,    # normal
        1     # cyst present
        
    ],
    default=np.nan
)

print(f"{col} unique values after process:\n", df1[col].unique())

-- Choroid Plexus
choroid_plexus_anomaly_scan unique values:
 ['نرمال' '7' 'کیست']
choroid_plexus_anomaly_scan unique values after process:
 [0. 1.]

In [30]:
print("-- Cavum Septum Pellucidum")
col = "cavum_septum_pellucidum_anomaly_scan"
print(f"{col} unique values:\n", df1[col].unique())

s = df1[col].astype(str).str.strip()

df1[col] = np.select(
    [
        s.str.contains('نرمال|ن$|نزمال', na=False),
        s.str.contains(r'\d', na=False)
    ],
    [
        # 1,   # abnormal (THIS MAY CHANGE IN OTHER FILES!!!!)
        0,   # normal
        0    # numeric size -> normal
    ],
    default=np.nan
)

print(f"{col} unique values after process:\n", df1[col].unique())

-- Cavum Septum Pellucidum
cavum_septum_pellucidum_anomaly_scan unique values:
 ['نرمال']
cavum_septum_pellucidum_anomaly_scan unique values after process:
 [0.]

In [31]:
print("-- Falx Cerebri Midline")
col = "falx_cerebri_midline_anomaly_scan"
print(f"{col} unique values:\n", df1[col].unique())

s = df1[col].astype(str).str.strip()

# 0 = normal (falx present) & 1 = abnormal / absent
df1[col] = np.select(
    [
        s.str.contains('نرمال|ن$|نزمال', na=False)
        # s.str.contains('نبود', na=False),
    ],
    [
        0  # normal
        # 1   # abnormal (THIS MAY CHANGE IN OTHER FILES!!!!)
    ],
    default=np.nan
)

print(f"{col} unique values after process:\n", df1[col].unique())

-- Falx Cerebri Midline
falx_cerebri_midline_anomaly_scan unique values:
 ['نرمال']
falx_cerebri_midline_anomaly_scan unique values after process:
 [0.]

## Columns (BA-BP)

In [32]:
# print(df1[df1[col]== ""]["index"])
# print(df1[df1[col]== ""]["index"])
# print(df1[df1[col]== ""]["index"])
# print(df1[df1[col]== ""]["index"])

In [33]:
print("-- Evaluation of Orbital Cavity")
col = "orbital_cavity_eval"
print(f"{col} unique values:\n", df1[col].unique())

s = df1[col].astype(str).str.strip()

df1[col] = np.select(
    [
        s.str.contains('نرمال|نزمال|نبود', na=False),        
        s.str.contains('غیر|abnormal|ناهنجار', na=False)
    ],
    [
        0,  # normal
        1   # abnormal (future safe)
    ],
    default=np.nan
)
print(f"{col} unique values after process:\n", df1[col].unique())

-- Evaluation of Orbital Cavity
orbital_cavity_eval unique values:
 ['نرمال']
orbital_cavity_eval unique values after process:
 [0.]

In [34]:
print("-- Evaluation of Upper Lip")
col = "upper_lip_eval"
print(f"{col} unique values:\n", df1[col].unique())

s = df1[col].astype(str).str.strip().str.lower()

df1[col] = np.select(
    [
        s.str.contains('نرمال|نزمال|normal|نبود', na=False),
        s.str.contains('cleft|شکاف|abnormal', na=False)
    ],
    [
        0,  # normal
        1   # abnormal (future safe)
    ],
    default=np.nan
)
print(f"{col} unique values after process:\n", df1[col].unique())

-- Evaluation of Upper Lip
upper_lip_eval unique values:
 ['نرمال']
upper_lip_eval unique values after process:
 [0.]

In [35]:
print("-- Evaluation of Heart")
col = "fetal_heart_eval"
print(f"{col} unique values:\n", df1[col].unique())

s = df1[col].astype(str).str.strip().str.lower()

df1[col] = np.select(
    [
        s.str.contains('سوفل|murmur|unnormal|mr', na=False),
        s.str.contains('نرمال|نزمال|normal|نبود', na=False)
    ],
    [
        1,   # abnormal
        0    # normal
    ],
    default=np.nan
)
print(f"{col} unique values after process:\n", df1[col].unique())

-- Evaluation of Heart
fetal_heart_eval unique values:
 ['نرمال']
fetal_heart_eval unique values after process:
 [0.]

In [36]:
print("-- Evaluation of Heart Chambers")
col = "fetal_heart_chambers_eval"
print(f"{col} unique values:\n", df1[col].unique())

s = df1[col].astype(str).str.strip().str.lower()

df1[col] = np.select(
    [
        s.str.contains('فوکوس|echogenic|اکوژن', na=False),  # Echogenic intracardiac focus (EIF) = white dot in heart -> usually marked
        s.str.contains('نرمال|نزمال|normal|نبود', na=False)
    ],
    [
        1,   # abnormal
        0    # normal
    ],
    default=np.nan
)
print(f"{col} unique values after process:\n", df1[col].unique())

-- Evaluation of Heart Chambers
fetal_heart_chambers_eval unique values:
 ['نرمال' 'توده اکوژن ']
fetal_heart_chambers_eval unique values after process:
 [0. 1.]

In [37]:
print("-- Evaluation of Lungs")
col = "lungs_eval"
print(f"{col} unique values:\n", df1[col].unique())

s = df1[col].astype(str).str.strip().str.lower()

df1[col] = np.select(
    [
        s.str.contains('گرانتینگ', na=False),  
        s.str.contains('نرمال|نزمال|normal|نبود', na=False)
    ],
    [
        1,   # abnormal
        0    # normal
    ],
    default=np.nan
)
print(f"{col} unique values after process:\n", df1[col].unique())

-- Evaluation of Lungs
lungs_eval unique values:
 ['نرمال']
lungs_eval unique values after process:
 [0.]

In [38]:
print("-- Evaluation of Diaphragm")
col = "diaphragm_eval"
print(f"{col} unique values:\n", df1[col].unique())

s = df1[col].astype(str).str.strip().str.lower()

df1[col] = np.select(
    [
        s.str.contains('نرمال|نزمال|نرما|normal|نبود', na=False),
        s.str.contains('hernia|فتق|abnormal', na=False)
    ],
    [
        0,  # normal
        1   # abnormal (future-safe)
    ],
    default=np.nan
)
print(f"{col} unique values after process:\n", df1[col].unique())

-- Evaluation of Diaphragm
diaphragm_eval unique values:
 ['نرمال']
diaphragm_eval unique values after process:
 [0.]

In [39]:
print("-- Evaluation of abd wall")
col = "abd_wall_nb_eval"

df1[col] = df1[col].str.strip()
print(f"{col} unique values:\n", df1[col].unique())

# Set normals to 0 and others to nan
mask = df1[col].astype(str).str.contains("نرما|نزمال|نبود", na=False)
df1[col] = np.where(mask, 0, np.nan)

print(f"{col} unique values after process:\n", df1[col].unique())

-- Evaluation of abd wall
abd_wall_nb_eval unique values:
 ['نرمال']
abd_wall_nb_eval unique values after process:
 [0.]

In [40]:
print("-- Evaluation of Stomach")
col = "stomach_eval"

df1[col] = df1[col].str.strip()
print(f"{col} unique values:\n", df1[col].unique())

# Set normals to 0 and others to nan
mask = df1[col].astype(str).str.contains("نرمال|نزمال|نبود", na=False)
df1[col] = np.where(mask, 0, np.nan)

print(f"{col} unique values after process:\n", df1[col].unique())

-- Evaluation of Stomach
stomach_eval unique values:
 ['نرمال']
stomach_eval unique values after process:
 [0.]

In [41]:
print("-- Evaluation of Kidney")
col = "kidney_eval"
print(f"{col} unique values:\n", df1[col].unique())

s = df1[col].astype(str).str.strip().str.lower()

df1[col] = np.select(
    [
        s.str.contains('پیلکتازیس|pyelectasis|pylectasis|abnormal', na=False),
        s.str.contains('نرمال|نزمال|normal|نبود', na=False)
    ],
    [
        1,  # abnormal
        0   # normal
    ],
    default=np.nan
)
print(f"{col} unique values after process:\n", df1[col].unique())

-- Evaluation of Kidney
kidney_eval unique values:
 ['نرمال' 'نرمال 18']
kidney_eval unique values after process:
 [0.]

In [42]:
print("-- Evaluation of Bladder")
col = "fetal_bladder_eval" 

df1[col] = df1[col].str.strip()
print(f"{col} unique values:\n", df1[col].unique())

# Set normals to 0 and others to nan
mask = df1[col].astype(str).str.contains("نرمال|نزمال|نبود|طبیعی|نمرال", na=False)
df1[col] = np.where(mask, 0, np.nan)

print(f"{col} unique values after process:\n", df1[col].unique())

-- Evaluation of Bladder
fetal_bladder_eval unique values:
 ['نرمال' 'نمرال' 'نرمال 7*4']
fetal_bladder_eval unique values after process:
 [0.]

In [43]:
print("-- Evaluation of Placenta Vessels")
col = "placenta_vessels_eval" 
print(f"{col} unique values:\n", df1[col].unique())

s = df1[col].astype(str).str.strip().str.lower()

df1[col] = np.select(
    [
        s.str.contains('sua|یک شریان', na=False),
        s.str.contains('نرمال|نزمال|normal|نبود', na=False)
    ],
    [
        1,  # abnormal
        0   # normal
    ],
    default=np.nan
)
print(f"{col} unique values after process:\n", df1[col].unique())

-- Evaluation of Placenta Vessels
placenta_vessels_eval unique values:
 ['نرمال']
placenta_vessels_eval unique values after process:
 [0.]

In [44]:
print("-- Evaluation of Limbs")
col = "fetal_limbs_eval" 
print(f"{col} unique values:\n", df1[col].unique())

s = df1[col].astype(str).str.strip().str.lower()

df1[col] = np.select(
    [
        s.str.contains('club|foot|انگشت|polydact|دیستونی', na=False),
        s.str.contains('نرمال|نزمال|normal|نبود', na=False)
    ],
    [
        1,  # abnormal
        0   # normal
    ],
    default=np.nan
)
print(f"{col} unique values after process:\n", df1[col].unique())

-- Evaluation of Limbs
fetal_limbs_eval unique values:
 ['نرمال']
fetal_limbs_eval unique values after process:
 [0.]

In [45]:
print("-- Evaluation of nb Attachment")
col = "nb_attachment_eval" 

df1[col] = df1[col].str.strip()
print(f"{col} unique values:\n", df1[col].unique())

# Set normals to 0 and others to nan
mask = df1[col].astype(str).str.contains("نرما|نزمال|نبود", na=False)
df1[col] = np.where(mask, 0, np.nan)

print(f"{col} unique values after process:\n", df1[col].unique())

-- Evaluation of nb Attachment
nb_attachment_eval unique values:
 ['نرمال']
nb_attachment_eval unique values after process:
 [0.]

In [46]:
print("-- Evaluation of Spinal Processes")
col = "spinal_processes_eval" 
print(f"{col} unique values:\n", df1[col].unique())

s = df1[col].astype(str).str.strip().str.lower()

df1[col] = np.select(
    [
        s.str.contains('spina|open spine|myelomeningocele|meningocele', na=False),
        s.str.contains('نرمال|نزمال|normal|نبود|ساکروکوکسیژئوس', na=False)
    ],
    [
        1,  # abnormal spine findings (future safe)
        0   # normal
    ],
    default=np.nan
)
print(f"{col} unique values after process:\n", df1[col].unique())

-- Evaluation of Spinal Processes
spinal_processes_eval unique values:
 ['نرمال']
spinal_processes_eval unique values after process:
 [0.]

In [47]:
print("-- Preeclampsia")
col = "preeclampsia"
print(f"{col} unique values:\n", df1[col].unique())

s = df1[col].astype(str).str.strip().str.lower()

df1[col] = np.select(
    [
        s.str.contains('ندا', na=False),
        s.str.contains('دارد|داشته', na=False)
    ],
    [
        0,  # normal
        1   # abnormal
    ],
    default=np.nan
)
print(f"{col} unique values after process:\n", df1[col].unique())

-- Preeclampsia
preeclampsia unique values:
 ['ندارد' 'دارد' nan]
preeclampsia unique values after process:
 [ 0.  1. nan]

# Numeric Columns
35 columns

## Columns (A-Z)

In [48]:
print("-- Check id")
check_null_dup(df1, "id")

-- Check id
No Null id
Duplicated id!
     index         id
17      18  2597467.0
19      20  2597467.0
23      24   470102.0
24      25   470102.0
60      61  2123023.0
61      62  2123023.0
70      71  2228158.0
71      72  2228158.0
115    116  2305384.0
118    119  2305384.0
120    121  1343029.0
121    122  1343029.0

In [49]:
# fill nan data for duplicated ids (Trick!)
df1.loc[df1["index"]== 71, ["moth_weight", "moth_height"]] = ["71", "169"]
df1.loc[df1["index"]== 116, ["moth_weight", "moth_height"]] = ["54", "150"]
df1.loc[df1["index"]== 121, ["moth_height"]] = ["165"]
df1.loc[df1["index"]== 62, ["moth_height"]] = ["160"]

In [50]:
print("-- Check age")
col = "moth_age"

# Check that all mother ages are numeric, > 10, and positive
print("Wrong Ages:")
print(df1[~pd.to_numeric(df1[col], errors="coerce").gt(10)][["index", col]])

-- Check age
Wrong Ages:
Empty DataFrame
Columns: [index, moth_age]
Index: []

In [51]:
print("-- Check weight")
col_w = "moth_weight"
# print(f"{col_w} unique values:\n", df1[col_w].unique())

# First solve the problem of two records (Trick!)
df1.loc[df1[col_w]=='45-60', col_w] = '52.5'  # save the average
df1.loc[df1[col_w]=='110-116', col_w] = '113'  # save the average

# extract numbers
reg_exp = r'(\d+\.?\d*)'
df1 = user_regex(df1, col_w, reg_exp)

-- Check weight
moth_weight unique values:
 ['ندارد' '78.8' '71' '91' '60' '86' '76' '61' '70' '57' '84' '65' '94'
 '73' '69' '53' '77' '50' nan '72' '113' '78' '52.5' '92' '93' '63' '67'
 '79' '54' '64' '74']
moth_weight unique values after process:
 [  nan  78.8  71.   91.   60.   86.   76.   61.   70.   57.   84.   65.
  94.   73.   69.   53.   77.   50.   72.  113.   78.   52.5  92.   93.
  63.   67.   79.   54.   64.   74. ]

In [52]:
print("-- Check Height")
col_h = "moth_height"

# extract numbers
reg_exp = r'(\d+\.?\d*)'
df1 = user_regex(df1, col_h, reg_exp)

-- Check Height
moth_height unique values:
 ['ندارد' '166' '173' '162' '151' '154' '164' '163' '165' '155' '160' '170'
 '169' '159' nan '158' '167' '157' '150' '148']
moth_height unique values after process:
 [ nan 166. 173. 162. 151. 154. 164. 163. 165. 155. 160. 170. 169. 159.
 158. 167. 157. 150. 148.]

In [53]:
print("-- Number of Pregnancies")
col = "num_preg"
df1 = not_numbers_to_nan(df1, col)


print("\n-- Number of Births")
col = "num_births"
df1 = not_numbers_to_nan(df1, col)


print("\n-- Number of Stillborns")
col = "num_stillborns"
df1 = not_numbers_to_nan(df1, col)


print("\n-- Number of Maternal Deaths")
col = "num_maternal_deaths"
df1 = not_numbers_to_nan(df1, col)


print("\n-- Number of Abortions")
col = "cnt_abortions"
df1 = not_numbers_to_nan(df1, col)

-- Number of Pregnancies
num_preg unique values:
 ['2' '1' '4' 'گزارش نشده' '3' '5' 'ندارد']
num_preg unique values after process:
 [ 2.  1.  4. nan  3.  5.]

-- Number of Births
num_births unique values:
 ['2' '1' '4' 'گزارش نشده' '3' '5' 'ندارد']
num_births unique values after process:
 [ 2.  1.  4. nan  3.  5.]

-- Number of Stillborns
num_stillborns unique values:
 ['0' 'گزارش نشده' 'ندارد']
num_stillborns unique values after process:
 [ 0. nan]

-- Number of Maternal Deaths
num_maternal_deaths unique values:
 ['0' 'گزارش نشده' 'ندارد']
num_maternal_deaths unique values after process:
 [ 0. nan]

-- Number of Abortions
cnt_abortions unique values:
 ['0' 'گزارش نشده' '1' 'ندارد' '2']
cnt_abortions unique values after process:
 [ 0. nan  1.  2.]

In [54]:
print("-- Check Previous Diabetes")
col = "prev_diabetes"

# Normalize text
df1[col] = df1[col].astype(str).str.strip()

print(f"{col} unique values:\n", df1[col].unique())

# single record cleaning (Trick!)
df1.loc[df1[col] == "بله ( در بارداری اول ولی نرمال)", col] = "ندارد"

# gestational diabetes
gdm_mask = df1[col].str.contains("دیابت بارداری|GDM", na=False)

# no diabetes
no_mask = df1[col].str.contains("ندارد|خیر|خی|خیز", na=False)

# diabetes
dm_mask = df1[col].str.contains("بله|دارد", na=False)

df1[col] = np.select(
    [gdm_mask, no_mask, dm_mask],
    [2, 0, 1],
    default=np.nan
)

print(f"{col} unique values after process:\n", df1[col].unique())

-- Check Previous Diabetes
prev_diabetes unique values:
 ['ندارد' 'دیابت دارد']
prev_diabetes unique values after process:
 [0. 1.]

In [55]:
print("-- Check Blood Nitrogen Level")
col = "blood_nitrogen_level"
df1 = not_numbers_to_nan(df1, col)

-- Check Blood Nitrogen Level
blood_nitrogen_level unique values:
 ['درخواست نشده' '5.6' '9' '8.9' '7' '7.94' '15' '6' '12.3' '5' '4.8' '8'
 '9.34' '10.4' '10.75' '10.27' '10' '10.28' '9.6' '14' '19' '14.02' '6.8'
 '12' '7.6']
blood_nitrogen_level unique values after process:
 [  nan  5.6   9.    8.9   7.    7.94 15.    6.   12.3   5.    4.8   8.
  9.34 10.4  10.75 10.27 10.   10.28  9.6  14.   19.   14.02  6.8  12.
  7.6 ]

In [56]:
print("-- Level of Urine Creatinine")
col = "urine_creatinine_level"
df1 = not_numbers_to_nan(df1, col)

-- Level of Urine Creatinine
urine_creatinine_level unique values:
 ['درخواست نشده' nan '462' '920' '163.11']
urine_creatinine_level unique values after process:
 [   nan 462.   920.   163.11]

In [57]:
print("-- Fasting Blodd Glucose Value")
col = "fasting_blood_glucose"

print(f"{col} unique values:\n", df1[col].unique())

s = df1[col].astype(str)

df1[col] = (
    s.str.findall(r'\d+(?:\.\d+)?')    # find all numbers
    .apply(lambda x: min(map(float, x)) if len(x) > 0 else np.nan)  # get minimum number when there is more than two, and others to nan
)

print(f"{col} unique values after process:\n", df1[col].unique())

-- Fasting Blodd Glucose Value
fasting_blood_glucose unique values:
 ['89' '70' '92' '83' '74' '68' 'درخواست نشده' '97' '78' '71' '93' '87'
 '106' '95' '75' '91' '85' '81' '77' '64' '84' '79' '69' '86' '72' '90'
 '76' '73' '65' '94' '80' '101' '81.5' '82' '62' '51' '98']
fasting_blood_glucose unique values after process:
 [ 89.   70.   92.   83.   74.   68.    nan  97.   78.   71.   93.   87.
 106.   95.   75.   91.   85.   81.   77.   64.   84.   79.   69.   86.
  72.   90.   76.   73.   65.   94.   80.  101.   81.5  82.   62.   51.
  98. ]

In [58]:
print("-- Thyroid Stimulating Hormone")
col = "thyroid_stimulating_hormone"
print(f"{col} unique values:\n", df1[col].unique())

# extract numbers, if there is two select the max (not in this data)
s = df1[col].astype(str)

df1[col] = (
    s.str.extract(r'(\d+[.,]?\d*)', expand=False)    # find all numbers
    .str.replace(",", ".", regex=False)  # replace 5,5 with 5.5
    .astype(float)
)

print(f"{col} unique values after process:\n", df1[col].unique())

-- Thyroid Stimulating Hormone
thyroid_stimulating_hormone unique values:
 ['1.8' '0.9' '0.82' '2' '2.8' '1' 'درخواست نشده' '2.5' '0.35' '4.4' '3.2'
 '1.4' '1.96' '1.25' '0.42' '1.26' '0.67' '2.3' '3.5' '2.52' '1.7' '2.6'
 '1.47' '2.7' '0.6' '2.2' '0.2' '0.87' '3.3' '0.7' '0.76' '1.75' '0.5'
 '0.85' '2.1' '1.9' '4.98' '3.7' '4' '1.55' '0.55' '1.1' '7.24' '1.5'
 '2.44' '1.6' '1.35' '4.8' '4.2' '0.56' '2.25' '1.2' '3.64' '10.5' '2.4'
 '3.75' '4.5' '1.08' '4.3' '2.73' '5' '0.63']
thyroid_stimulating_hormone unique values after process:
 [ 1.8   0.9   0.82  2.    2.8   1.     nan  2.5   0.35  4.4   3.2   1.4
  1.96  1.25  0.42  1.26  0.67  2.3   3.5   2.52  1.7   2.6   1.47  2.7
  0.6   2.2   0.2   0.87  3.3   0.7   0.76  1.75  0.5   0.85  2.1   1.9
  4.98  3.7   4.    1.55  0.55  1.1   7.24  1.5   2.44  1.6   1.35  4.8
  4.2   0.56  2.25  1.2   3.64 10.5   2.4   3.75  4.5   1.08  4.3   2.73
  5.    0.63]

In [59]:
print("-- Result of Nuchal Translucency Test")
col = "nuchal_translucency_test"
reg_exp = r'(\d+\.?\d*)'
df1 = user_regex(df1, col, reg_exp)

-- Result of Nuchal Translucency Test
nuchal_translucency_test unique values:
 ['درخواست نشده' '1.4' '1.41' '0.9' '1.99' '1.7' '1.6' '1.82' '1.2' '2.21'
 '1.79' '1.61' '2.4' '1' '1.32' '1.5']
nuchal_translucency_test unique values after process:
 [ nan 1.4  1.41 0.9  1.99 1.7  1.6  1.82 1.2  2.21 1.79 1.61 2.4  1.
 1.32 1.5 ]

## Columns (AA-AZ)

In [60]:
print("-- Result of Plasma Protein A")
col = "pregnancy_related_plasma_protein_a"
print(f"{col} unique values:\n", df1[col].unique())

# 1. Extract numbers and set all not numbers to nan
df1[col] = (
    df1[col]
    .str.extract(r'(\d+[.,-]?\d*)', expand=False)    # one or more digits + one or zero dot or comma or dash + zero or more digits
    .str.replace(",", ".", regex=False)  
    .str.replace("-", ".", regex=False)
    .astype(float)
)

print(f"{col} unique values after process:\n", df1[col].unique())

-- Result of Plasma Protein A
pregnancy_related_plasma_protein_a unique values:
 ['3830' '10.5' '3324' 'ندارد' 'درخواست نشده' '2.1' '1.3' '1888' '7.8'
 '3.07' '3330' '10.2' '13.04' '3.52' '6.94' '696' '48.3' '1.6' '1020'
 '29.4' '4710' '2805' '3177' '1.31' '3454' '2470' '6.3' '958' '6.72'
 '2.89' '10361' '24.3' '5860' '7048' '30.3' '3']
pregnancy_related_plasma_protein_a unique values after process:
 [3.8300e+03 1.0500e+01 3.3240e+03        nan 2.1000e+00 1.3000e+00
 1.8880e+03 7.8000e+00 3.0700e+00 3.3300e+03 1.0200e+01 1.3040e+01
 3.5200e+00 6.9400e+00 6.9600e+02 4.8300e+01 1.6000e+00 1.0200e+03
 2.9400e+01 4.7100e+03 2.8050e+03 3.1770e+03 1.3100e+00 3.4540e+03
 2.4700e+03 6.3000e+00 9.5800e+02 6.7200e+00 2.8900e+00 1.0361e+04
 2.4300e+01 5.8600e+03 7.0480e+03 3.0300e+01 3.0000e+00]

In [61]:
print("-- Free Beta-hCG")
col = "free_beta_hcg"
print(f"{col} unique values:\n", df1[col].unique())

# 1. Extract numbers and set all not numbers to nan
df1[col] = (
    df1[col]
    .str.extract(r'(\d+[.,-]?\d*)', expand=False)    # one or more digits + one or zero dot or comma or dash + zero or more digits
    .str.replace(",", ".", regex=False)  
    .str.replace("-", ".", regex=False)
    .astype(float)
)

print(f"{col} unique values after process:\n", df1[col].unique())

-- Free Beta-hCG
free_beta_hcg unique values:
 ['49' '29' '51' 'ندارد' 'درخواست نشده' '74.5' '104' '28' '35.6' '60.3'
 '21' '33.4' '10.09' '11.94' '43' '10.38' '37' '60.2' '41.2' '17' '21.6'
 '47' '76' '34' '31.8' '53.65' '24.6' '32' '48.4' '165.6' '63.1' '42' '71'
 '79.2' '12.26']
free_beta_hcg unique values after process:
 [ 49.    29.    51.      nan  74.5  104.    28.    35.6   60.3   21.
  33.4   10.09  11.94  43.    10.38  37.    60.2   41.2   17.    21.6
  47.    76.    34.    31.8   53.65  24.6   32.    48.4  165.6   63.1
  42.    71.    79.2   12.26]

In [62]:
print("-- Alpha Fetoprotein")
col = "alpha_fetoprotein"
reg_exp = r'(\d+\.?\d*)' 
df1 = user_regex(df1, col, reg_exp)

-- Alpha Fetoprotein
alpha_fetoprotein unique values:
 ['ندارد' '36.8' 'درخواست نشده' '44.1' '28.4' '22.07' '60' '16.79' '58'
 '40' '66' '31.97' '22.4' '27.9' '25.6' '44' '19.8' '13.5']
alpha_fetoprotein unique values after process:
 [  nan 36.8  44.1  28.4  22.07 60.   16.79 58.   40.   66.   31.97 22.4
 27.9  25.6  44.   19.8  13.5 ]

In [63]:
print("-- Esteriol")
col = "estriol"
# reomve 'ue3' for later number extraction
df1[col] = (
    df1[col]
    .astype(str)
    .str.lower()
    .str.replace('ue3=', '', regex=False)
    .str.strip()
)
reg_exp = r'(\d+\.?\d*)' 
df1 = user_regex(df1, col, reg_exp)

-- Esteriol
estriol unique values:
 ['ندارد' '3.9' 'درخواست نشده' '3.3' '2.59' '3.12' '3.71' '0.83' '0.93'
 '1.5' '2.42' '0.31' '0.65' '4.2' '1.832' '0.36' '2.2']
estriol unique values after process:
 [  nan 3.9   3.3   2.59  3.12  3.71  0.83  0.93  1.5   2.42  0.31  0.65
 4.2   1.832 0.36  2.2  ]

In [64]:
print("-- Inhibin-A")
col = "inhibin_a"
reg_exp = r'(\d+\.?\d*)'  # one or more digits + one or zero dots + zero or more digits
df1 = user_regex(df1, col, reg_exp)

-- Inhibin-A
inhibin_a unique values:
 ['ندارد' '294.2' 'درخواست نشده' '134.3' '158.6' '296.07' '52.65' '189'
 '223.8' '213' '642' '244' '407.7' '181.5' '321' '486' '219.8']
inhibin_a unique values after process:
 [   nan 294.2  134.3  158.6  296.07  52.65 189.   223.8  213.   642.
 244.   407.7  181.5  321.   486.   219.8 ]

In [65]:
print("-- BHCG Total")
col = "bhcg_total"
print(f"{col} unique values:\n", df1[col].unique())

# 1. Extract numbers and set all not numbers to nan
df1[col] = (
    df1[col]
    .str.extract(r'(\d+[.,-]?\d*)', expand=False)    # one or more digits + one or zero dot or comma or dash + zero or more digits
    .str.replace(",", ".", regex=False)  
    .str.replace("-", ".", regex=False)
    .astype(float)
)

print(f"{col} unique values after process:\n", df1[col].unique())

-- BHCG Total
bhcg_total unique values:
 ['ندارد' '28192' 'درخواست نشده' '20031' '19667' '14728' '10716' '41' '53'
 '10' '32160' '24.3' '51995' '36473' '38439' '10000' '24000' '15902'
 '26212']
bhcg_total unique values after process:
 [       nan 2.8192e+04 2.0031e+04 1.9667e+04 1.4728e+04 1.0716e+04
 4.1000e+01 5.3000e+01 1.0000e+01 3.2160e+04 2.4300e+01 5.1995e+04
 3.6473e+04 3.8439e+04 1.0000e+04 2.4000e+04 1.5902e+04 2.6212e+04]

In [66]:
print("-- Temporal Bone Diameter")
col = "temporal_bone_diameter"
df1 = clean_length_cols(df1, col)

print("\n-- Head Circumference")
col = "fetal_head_circumference"
df1 = clean_length_cols(df1, col)

print("\n-- Abdominal Circumference")
col = "fetal_abdominal_circumference"
df1 = clean_length_cols(df1, col)

print("\n-- Femur Length")
col = "fetal_femur_length"
df1 = clean_length_cols(df1, col)

-- Temporal Bone Diameter
temporal_bone_diameter unique values:
 ['41.53' 'منطبق با 18 هفتگی' '41' '42' 'مطابق با 18 هفتگی' '44' '46' '39'
 '40' '43' '45.9' '51' 'مطابق با 19 هفتگی' '42.9' '38' 'مطابق با 20 هفتگی'
 '49' '40.8' '39.5' '50' '44.2' '39.8' 'نرمال' '194' '41.8' '40.4' '53'
 '41.3' '52' '45' '39.6']
temporal_bone_diameter unique values after processing:
 [ 41.53    nan  41.    42.    44.    46.    39.    40.    43.    45.9
  51.    42.9   38.    49.    40.8   39.5   50.    44.2   39.8  194.
  41.8   40.4   53.    41.3   52.    45.    39.6 ]

-- Head Circumference
fetal_head_circumference unique values:
 ['152.41' 'منطبق با 18 هفتگی' '152' 'مطابق با 19 هفتگی'
 'مطابق با 18 هفتگی' '166' '177' '148' '168' '159' '167' '175' '161'
 '166.4' 'مطابق با 21 هفتگی' '155' '170' '153' '160' '151'
 'مطابق با 20 هفتگی' '165' '172' '164' '150' '148.4' '185' '156' '163'
 'نرمال' '154' '159.6' '149' '157' '28' '162' '200' '192' '145' '180'
 '173' '187']
fetal_head_circumference unique values after processing:
 [152.41    nan 152.   166.   177.   148.   168.   159.   167.   175.
 161.   166.4  155.   170.   153.   160.   151.   165.   172.   164.
 150.   148.4  185.   156.   163.   154.   159.6  149.   157.    28.
 162.   200.   192.   145.   180.   173.   187.  ]

-- Abdominal Circumference
fetal_abdominal_circumference unique values:
 ['127.73' 'منطبق با 18 هفتگی' '131' 'مطابق با 19 هفتگی'
 'مطابق با 18 هفتگی' '158' '155' '123' '145' 'گزارش نشده' '132' '146'
 '147' '135' '127.5' '155.8' 'مطابق با 21 هفتگی' '122' '125' '121' '133'
 '142' '124' 'مطابق با 20 هفتگی' '148' '136' '124.3' '153' '28' '37.2'
 '130' '126' '136.5' '138' 'نرمال' '128' '137' '270' '129' '167' '141'
 '134' '143' '163' '140']
fetal_abdominal_circumference unique values after processing:
 [127.73    nan 131.   158.   155.   123.   145.   132.   146.   147.
 135.   127.5  155.8  122.   125.   121.   133.   142.   124.   148.
 136.   124.3  153.    28.    37.2  130.   126.   136.5  138.   128.
 137.   270.   129.   167.   141.   134.   143.   163.   140.  ]

-- Femur Length
fetal_femur_length unique values:
 ['26.13' 'منطبق با 18 هفتگی' '27' 'مطابق با 19 هفتگی' 'مطابق با 18 هفتگی'
 '31' '25' '28' '34' '31.7' 'مطابق با 21 هفتگی' '26' 'مطابق با 20 هفتگی'
 '29' '32' '26.2' '30' '289' '470' '28.4' 'نرمال' '28.9' '38' '37' '35'
 '23' '40' '33' '36']
fetal_femur_length unique values after processing:
 [ 26.13    nan  27.    31.    25.    28.    34.    31.7   26.    29.
  32.    26.2   30.   289.   470.    28.4   28.9   38.    37.    35.
  23.    40.    33.    36.  ]

In [67]:
print("-- Weight Estimation")
col = "fetal_weight_estimation"
reg_exp = r'(\d{2,5})'   # between 2 to 5 digits
df1 = user_regex(df1, col, reg_exp)

-- Weight Estimation
fetal_weight_estimation unique values:
 ['222' '230' '246' '264' '245' '224' '339' '374' '227' '291' '220' '257'
 '314' '343' '260' '233' '304' '414' '282' '244' '223' '238' '210' '333'
 '240' '261' '270' '250' '217' '235' '328' '285' '237' '212' '206' '350'
 '241' '342' '268' '229' '300' '274' 'نرمال' '30' '243' '226' '263' '283'
 '242' '296' '281' '265' '292' '340' '273' '289' '500' '215' '460' '278'
 '410' '370' '253' '239' '252' '295' '219' '535' '267' '375' '360' '198'
 '288' '200' '236' '232' '287' '277' '396' nan '214' '293']
fetal_weight_estimation unique values after process:
 [222. 230. 246. 264. 245. 224. 339. 374. 227. 291. 220. 257. 314. 343.
 260. 233. 304. 414. 282. 244. 223. 238. 210. 333. 240. 261. 270. 250.
 217. 235. 328. 285. 237. 212. 206. 350. 241. 342. 268. 229. 300. 274.
  nan  30. 243. 226. 263. 283. 242. 296. 281. 265. 292. 340. 273. 289.
 500. 215. 460. 278. 410. 370. 253. 239. 252. 295. 219. 535. 267. 375.
 360. 198. 288. 200. 236. 232. 287. 277. 396. 214. 293.]

In [68]:
print("-- Cervical Length")
col = "cervical_length"
reg_exp = r'(\d{2})'    # exactly 2 digits
df1 = user_regex(df1, col, reg_exp)

-- Cervical Length
cervical_length unique values:
 ['گزارش نشده' '44' '36' '33' '32' '41' '37' '40' '39' '35' '38' '56' '45'
 'گزترش نشده' '34' '30' 'نرمال' '31' '42' '46' '25' '28' '43' '49' '48'
 '47']
cervical_length unique values after process:
 [nan 44. 36. 33. 32. 41. 37. 40. 39. 35. 38. 56. 45. 34. 30. 31. 42. 46.
 25. 28. 43. 49. 48. 47.]

In [69]:
print("-- Nuchal Skin Fold")
col = "nuchal_skin_fold"
reg_exp = r'(\d+\.?\d*)'
df1 = user_regex(df1, col, reg_exp)

-- Nuchal Skin Fold
nuchal_skin_fold unique values:
 ['3.64' '2' '6' '3.7' 'نرمال' '3.1' '4.1' '3' '3.4' '4' '3.3' '3.6' '3.8'
 '3.79' '4.3' '3.81' '3.2' '2.9' '3.5' '2.27' '3.44' '7' '4.8' '1.3' '1.5'
 '2.86' '2.5' '4.7' '4.6' '5.22' '3.49' '1.2' '1.6' '4.2' '4.5' '2.8'
 '2.6' '2.7' '2.3' '3.9' '5.9' '1.9' '5' '3.16' '3.77' '3.58']
nuchal_skin_fold unique values after process:
 [3.64 2.   6.   3.7   nan 3.1  4.1  3.   3.4  4.   3.3  3.6  3.8  3.79
 4.3  3.81 3.2  2.9  3.5  2.27 3.44 7.   4.8  1.3  1.5  2.86 2.5  4.7
 4.6  5.22 3.49 1.2  1.6  4.2  4.5  2.8  2.6  2.7  2.3  3.9  5.9  1.9
 5.   3.16 3.77 3.58]

In [70]:
print("-- Apgar")
col = "apgar"
df1 = not_numbers_to_nan(df1, col)

-- Apgar
apgar unique values:
 ['ندارد' '9' nan 'نبود' '8']
apgar unique values after process:
 [nan  9.  8.]

In [71]:
print("-- Lateral Ventricles Size")
col = "lateral_ventricles_size_anomaly_scan"
print(f"{col} unique values:\n", df1[col].unique())

# Extract numbers from strings and make all others, nan
df1[col] = (
    df1[col]
    .str.extract(r'(\d+[.,]?\d*)', expand=False)    # one or more digits + one or zero dot or comma + zero or more digits
    .str.replace(",", ".", regex=False)  # replace 5,5 with 5.5
    .astype(float)
)

print(f"{col} unique values after process:\n", df1[col].unique())

-- Lateral Ventricles Size
lateral_ventricles_size_anomaly_scan unique values:
 ['6.94' '5.5' 'نرمال' '7' '5.4' '6.9' '8' '8.2' '6.42' '7.9' '6.1' '8.1'
 '7.8' '5' '6.6' '6.4' '5.1' '5.9' '5.8' '7.7' '7.5' '7.1' '9.07' '6.5'
 '6' '3.9' '7.39' '7.4' '7.47' '8.5' '9.1' '9' '8.9' '6.8' '5.7' '7.6'
 '10' '7.3']
lateral_ventricles_size_anomaly_scan unique values after process:
 [ 6.94  5.5    nan  7.    5.4   6.9   8.    8.2   6.42  7.9   6.1   8.1
  7.8   5.    6.6   6.4   5.1   5.9   5.8   7.7   7.5   7.1   9.07  6.5
  6.    3.9   7.39  7.4   7.47  8.5   9.1   9.    8.9   6.8   5.7   7.6
 10.    7.3 ]

In [72]:
print("-- Evaluation of Brain Size")
col = "brain_size_eval"
print(f"{col} unique values:\n", df1[col].unique())

# 1. Changed the two wrong records to nan (Trick!)
df1.loc[df1[col]=='18.25..', col] = '18.25'

# 2. Extract numbers from strings and make all others, nan
df1[col] = (
    df1[col]
    .str.extract(r'(\d+[.,]?\d*)', expand=False)    # one or more digits + one or zero dot or comma + zero or more digits
    .str.replace(",", ".", regex=False)  # replace 5,5 with 5.5
    .astype(float)
)

print(f"{col} unique values after process:\n", df1[col].unique())

-- Evaluation of Brain Size
brain_size_eval unique values:
 ['18.5' '18' 'نرمال' '18.8' '18.1' '18.2' '19.4' '18.9' '20.3' '20' '18.6'
 '19.8' '21.7' '17' '19' '20.8' '19.7' '18.3' '19.16' '19.2' '19.5' '23'
 '17.8' '19.3' '18.7' '18.25..' '22.2' '16.8' '21' '17.5' '17.4']
brain_size_eval unique values after process:
 [18.5  18.     nan 18.8  18.1  18.2  19.4  18.9  20.3  20.   18.6  19.8
 21.7  17.   19.   20.8  19.7  18.3  19.16 19.2  19.5  23.   17.8  19.3
 18.7  18.25 22.2  16.8  21.   17.5  17.4 ]

In [73]:
print("-- Evaluation of Cisterna Magna")
col = "cisterna_magna_eval"

print(f"{col} unique values:\n", df1[col].unique())

# Extract numbers from strings and make all others, nan
df1[col] = (
    df1[col]
    .str.extract(r'(\d+[.,]?\d*)', expand=False)    # one or more digits + one or zero dot or comma + zero or more digits
    .str.replace(",", ".", regex=False)  # replace 5,5 with 5.5
    .astype(float)
)

print(f"{col} unique values after process:\n", df1[col].unique())

-- Evaluation of Cisterna Magna
cisterna_magna_eval unique values:
 ['4.17' '4' 'نرمال' '4.7' '6.5' '5.8' '6.7' '3.9' '4.4' '4.8' '4.77' '5.3'
 '3.4' '5' '4.5' '3.37' '3.7' '5.2' '3' '5.1' '3.44' '6.2' '3.1' '6.1'
 '4.73' '2.6' '3.5' '4.3' '4.1' '3.69' '5.6' '4.9' '4.49' '6' '4.2' '5.5'
 '3.2' '7.1']
cisterna_magna_eval unique values after process:
 [4.17 4.    nan 4.7  6.5  5.8  6.7  3.9  4.4  4.8  4.77 5.3  3.4  5.
 4.5  3.37 3.7  5.2  3.   5.1  3.44 6.2  3.1  6.1  4.73 2.6  3.5  4.3
 4.1  3.69 5.6  4.9  4.49 6.   4.2  5.5  3.2  7.1 ]

## Columns (BA-BP)

In [74]:
print("-- Evaluation of Lips and Nose")
col = "lips_nose_eval"
print(f"{col} unique values:\n", df1[col].unique())

# Extract numbers from strings and make all others, nan
df1[col] = (
    df1[col]
    .str.extract(r'(\d+[.,]?\d*)', expand=False)    # one or more digits + one or zero dot or comma + zero or more digits
    .str.replace(",", ".", regex=False)  # replace 5,5 with 5.5
    .astype(float)
)

print(f"{col} unique values after process:\n", df1[col].unique())

-- Evaluation of Lips and Nose
lips_nose_eval unique values:
 ['نرمال' '6' '4.7' '4' '6.1' '6.5' '6.4' '5.5' '5.1' '4.1' '6.6' '5.9' '5'
 '4.9' '5.2' '4.26' '4.8' '6.8' '5.3' '6.2' '5.7' '6.3' '4.6' '6.9' '5.6'
 '4.3' '5.4' '7.3' '4.2' '7' '5.55' '5.44' '4.5' '7.1' '6.7' '5.8']
lips_nose_eval unique values after process:
 [ nan 6.   4.7  4.   6.1  6.5  6.4  5.5  5.1  4.1  6.6  5.9  5.   4.9
 5.2  4.26 4.8  6.8  5.3  6.2  5.7  6.3  4.6  6.9  5.6  4.3  5.4  7.3
 4.2  7.   5.55 5.44 4.5  7.1  6.7  5.8 ]

In [75]:
print("-- Evaluation of Heart Rate")
col = "fetal_heart_rate_eval"

# 1. Replace all normal or naturals with 135
df1.loc[df1[col].astype(str).str.contains("نرمال|طبیعی", case=False, na=False), col] = '135'

# 2. Keep numbers
reg_exp = r'(\d{3})'    # exactly 3 digits
df1 = user_regex(df1, col, reg_exp)

-- Evaluation of Heart Rate
fetal_heart_rate_eval unique values:
 ['136' '156' '135' '151' 'گزارش نشده' '142' '153' '140' '159' '152' '148'
 '145' '147' '146' '138' '160' '143' '154' '150' '144' '158' '149' '155'
 '133' '157' '139' '141']
fetal_heart_rate_eval unique values after process:
 [136. 156. 135. 151.  nan 142. 153. 140. 159. 152. 148. 145. 147. 146.
 138. 160. 143. 154. 150. 144. 158. 149. 155. 133. 157. 139. 141.]

# Data after Cleaning Columns

In [76]:
df1.head()

,index,id,moth_age,moth_weight,moth_height,parent_relat,race,num_preg,num_births,num_stillborns,...,diaphragm_eval,abd_wall_nb_eval,stomach_eval,kidney_eval,fetal_bladder_eval,placenta_vessels_eval,fetal_limbs_eval,nb_attachment_eval,spinal_processes_eval,preeclampsia
0,1,2476491.0,29,NaN,NaN,NaN,NaN,2.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,2368629.0,18,NaN,NaN,0.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,2629535.0,31,NaN,NaN,0.0,1.0,2.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,1012353.0,36,NaN,NaN,0.0,0.0,4.0,4.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,2615589.0,25,78.8,NaN,NaN,NaN,4.0,4.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [77]:
df1.to_csv('cleaned_data/n2_cleaned.csv', index=False)